[package]
name = "ardl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
keyed_priority_queue = "0.4.1"
num_enum = "0.5.7"
